import { Toaster } from "react-hot-toast";


import './globals.css'
import Navbar from "../../components/Navbar";
import Providers from "../../components/Providers";

export const metadata = {
  title: 'Market²',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  )
}